### ISSUE TITLE
Duplication of gsis_id in 2020 rosters 

### ISSUE THREAD

**Issue by awgymer** [mrcaseb/nflfastR#103]
There is some very limited `gsis_id` duplication in the 2020 rosters.
I identified the following duplications when grouping by `gsis_id` and `team`.
```
    season team position               full_name espn_id     gsis_id
 1:   2020 <NA>       WR         Jordan Williams      NA  00-0032876
 2:   2020 <NA>       WR Jordan Williams-Lambert 2972065  00-0032876
 3:   2020 <NA>       NT             Jegs Jegede 4408860  00-0035027
 4:   2020 <NA>       NT             Jegs Jegede 4408860  00-0035027
 5:   2020 <NA>       WR       Terrell Sinkfield   16414  00-0029981
 6:   2020 <NA>       WR       Terrell Sinkfield   16414  00-0029981
 7:   2020  NYG       CB        Brandon Williams 2972286  00-0032769
 8:   2020  NYG       CB        Brandon Williams   16313  00-0032769
 9:   2020  CHI       WR            Reggie Davis 2979174  00-0033815
10:   2020  CHI       WR            Reggie Davis 3043134  00-0033815
11:   2020  WAS       FS           Jeremy Reaves 3125248  00-0034465
12:   2020  WAS       SS           Jeremy Reaves      NA  00-0034465
```

Not entirely sure what the cause is, but half seem to be actually the same player doubled up and the team is `NA`, 2 are actually different players (as shown by different ESPN IDs) with similar/same names, and the last is the same player with a second position.

**Comment by mrcaseb** [comment]
Code to reproduce

``` r
library(tidyverse)
library(nflfastR)

roster <- fast_scraper_roster(2020)

dupl_ids <- roster %>% count(gsis_id) %>% filter(n > 1, !is.na(gsis_id))

roster %>% filter(gsis_id %in% dupl_ids$gsis_id) %>% select(full_name, birth_date:weight, gsis_id:rotowire_id)
```

<img width="874" alt="Bildschirmfoto 2020-09-26 um 21 53 24" src="https://user-images.githubusercontent.com/38586519/94349225-e123e680-0042-11eb-88e0-0462131f5ac7.png">


Memo to myself: Use last update column in source to filter older entries will solve most of the problems

**Comment by mrcaseb** [comment]
This is fixed. See https://github.com/mrcaseb/nflfastR-roster/issues/2#issuecomment-700141358
