### ISSUE TITLE
air_yards not corresponding to play-by-play

### ISSUE THREAD

**Issue by MargareeMan** [mrcaseb/nflfastR#104]
I noticed a few discrepancies in the air_yards variable versus the pbp.  I did not research beyond four examples I found in looking at air_yards less than -10 in 2020 season.  

game_id,drive,play_id,week,air_yards,desc
2020_01_CHI_DET,2,346,1,-36,(9:09) (Shotgun) 10-M.Trubisky pass incomplete short left to 80-J.Graham [59-R.Ragland].
2020_01_GB_MIN,3,660,1,-21,(1:58) (Shotgun) 12-A.Rodgers pass incomplete short right to 87-J.Sternberger.
2020_01_SEA_ATL,17,3763,1,-82,"(9:38) (No Huddle, Shotgun) 2-M.Ryan pass short right to 18-C.Ridley for 18 yards, TOUCHDOWN."
2020_02_KC_LAC,16,3318,2,-38,"(12:58) (Shotgun) 15-P.Mahomes pass short right to 10-T.Hill for 54 yards, TOUCHDOWN.
The Replay Official reviewed the runner was not down by contact ruling, and the play was Upheld. The ruling on the field stands."

I apologize in advance if this is my mistake or a known issue.

**Comment by guga31bb** [comment]
These should be fixed if you re-download the data- I actually just checked this yesterday. Closing this but please let us know if it persists.
