### ISSUE TITLE
Add variable for "ball handler" (rusher or receiver)

### ISSUE THREAD

**Issue by mrcaseb** [mrcaseb/nflfastR#121]
I got this question via twitter if there is a variable or an easy way to get the "ball handler" (rusher or receiver) on a play. This would be the rushing/receiving counterpart to `name` and `id` and I see why some people could be intereted in it (epsecially fantasy guys).

I think we should add this to `clean_pbp()` during the next off-season.

Something like 
```r
pbp %>% 
  dplyr::mutate(
    handler = case_when(
      !is.na(rusher) ~ rusher,
      is.na(rusher) & !is.na(receiver) ~ receiver,
      TRUE ~ passer
    ),
    handler_id = case_when(
      !is.na(rusher_id) ~ rusher_id,
      is.na(rusher_id) & !is.na(receiver_id) ~ receiver_id,
      TRUE ~ passer_id
    )
  )
```

**Comment by guga31bb** [comment]
Putting this here so I don't forget but I think `action_player` is my favorite https://twitter.com/benbbaldwin/status/1358139028500062209

**Comment by guga31bb** [comment]
For discussion: do we want to use the NFL-provided ones (eg `rusher_player_name` and `rusher_player_id`) or the cleaned ones (`rusher` and `rusher_id`) for this? If this is going to be primarily used for fantasy purposes, I would think the former since that's how to calculate the official stats (because it doesn't include plays negated by penalty).

**Comment by mrcaseb** [comment]
> For discussion: do we want to use the NFL-provided ones (eg `rusher_player_name` and `rusher_player_id`) or the cleaned ones (`rusher` and `rusher_id`) for this? If this is going to be primarily used for fantasy purposes, I would think the former since that's how to calculate the official stats (because it doesn't include plays negated by penalty).

I just wanted to ask this exact question. My initial idea with `handler` was that we do both in the same pattern. `handler` (including penalties) and `handler_player_name` excluding penalties. 

I kind of like the idea of having both.

**Comment by mrcaseb** [comment]
> Putting this here so I don't forget but I think `action_player` is my favorite https://twitter.com/benbbaldwin/status/1358139028500062209

How about `carrier`, `carrier_id` and `carrier_player_name`, `carrier_player_id`?

**Comment by guga31bb** [comment]
I think `carrier` makes it sound too much like rushing plays only (i.e. it's not obvious that it includes WRs on incomplete passes).

But having both sounds good to me whatever we decide on the name

**Comment by guga31bb** [comment]
Here is my current vote
```
      dplyr::mutate(
        fantasy_player = case_when(
          !is.na(.data$rusher_player_name) ~ .data$rusher_player_name,
          is.na(.data$rusher_player_name) & !is.na(.data$receiver_player_name) ~ .data$receiver_player_name,
          TRUE ~ NA_character_
        ),
        fantasy_player_id = case_when(
          !is.na(.data$rusher_player_id) ~ .data$rusher_player_id,
          is.na(.data$rusher_player_id) & !is.na(.data$receiver_player_id) ~ .data$receiver_player_id,
          TRUE ~ NA_character_
        ),
        fantasy = case_when(
          !is.na(.data$rusher) ~ .data$rusher,
          is.na(.data$rusher) & !is.na(.data$receiver) ~ .data$receiver,
          TRUE ~ NA_character_
        ),
        fantasy_id = case_when(
          !is.na(.data$rusher_id) ~ .data$rusher_id,
          is.na(.data$rusher_id) & !is.na(.data$receiver_id) ~ .data$receiver_id,
          TRUE ~ NA_character_
        )
      )
```
I started with `action` instead of `fantasy` but just having `action` itself as a column feels weird.

I think I just need to add this to `clean_pbp()` and the `any_of` in `helper_decode_player_ids.R`
