### ISSUE TITLE
Add "out_of_bounds" variable

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#122]
I'm wondering if we could get an out_of_bounds variable added to the data set for plays in which a player runs or is pushed out of bounds. This variable would help analyze things like tackle rates and play selection in late-game situations.

**Comment by mrcaseb** [comment]
The only way to do this is parsing the play description. Does anyone know if `desc` uses _"out of bounce"_ reliably?

**Comment by TheMathNinja** [comment]
In my brief research/parsing of 2020, I’ve experienced “desc” to pretty reliably classify as “ran ob,” “pushed ob,” or “sacked ob.” One of the easiest ways to check is filter by plays without an incomplete, TD, or tackle recorded. At least 2020 showed reliable descriptions of the 3 above ob variations via this filter.
