### ISSUE TITLE
Roughing the passer plays not being tagged with qb_hit == 1

### ISSUE THREAD

**Issue by youknowwhymhere** [mrcaseb/nflfastR#135]
I was looking at the PBP for the BUF-SEA game where Wilson got hit supposedly 16 times, a YTD high. When I reconciled against the [gamebook PBP](https://nflcdns.nfl.com/liveupdate/gamecenter/58290/BUF_Gamebook.pdf), I found some plays are not being tagged with qb_hit == 1, though there were hits on him. Could these be handled, please? It would make querying for these much easier.

game_id | play_id | desc
-- | -- | --
2020_09_SEA_BUF | 1272 | (9:52) (Shotgun) 3-R.Wilson pass incomplete deep left to 14-D.Metcalf   (27-T.White) [91-E.Oliver]. Penalty on BUF-91-E.Oliver, Roughing the Passer,   declined. PENALTY on BUF-27-T.White, Defensive Pass Interference, 25 yards,   enforced at SEA 22 - No Pla
2020_09_SEA_BUF | 2916 | (3:44) 3-R.Wilson pass incomplete deep right to 16-T.Lockett   [55-J.Hughes]. PENALTY on BUF-55-J.Hughes, Roughing the Passer, 15 yards,   enforced at BUF 44 - No Play.

**Comment by mrcaseb** [comment]
The `qb_hit` variable is relying on the underlying data by the NFL. So the one thing we can do is hoping they fix it in the next two days. We update the data every Wednesday night to get the latest fixes by the NFL. 

I would appreciate if you check the data in Thursday again and see if it's corrected.

**Comment by guga31bb** [comment]
It's also possible these don't count as QB hits in the official stats since they were negated plays

**Comment by TheMathNinja** [comment]
I believe @guga31bb is correct here. I think stat corrections will not change these. "Times a QB was hit" is a different stat than "QB Hits stats recorded."

**Comment by youknowwhymhere** [comment]
Thank you all for your comments. The question I had is not regarding an official stat on QB hits. Currently, there are 11 plays with qb_hit == 1 for Wilson in this game. Media claims he was hit 16 times. That's a non-trivial difference, hence trying to figure out if this is represented in the PBP. I'll wait till Thursday and take a look. No big deal either ways, but kinda good to know the limits of this data.

**Comment by TheMathNinja** [comment]
It’s non-trivial but a big difference lies in vocabulary. The stat “QB Hit” is only recorded if:
1. The QB is literally knocked to the ground
2. The play is not called back via penalty or anything else.

The 5-play difference is probably in these two facts. Looks like we found at least two that satisfied the second criteria. It would be unsurprising if Wilson took 3 hard shots in the game that this media was calling a “hit” but they didn’t knock him to the ground so it’s not classified as a “QB Hit” stat

**Comment by youknowwhymhere** [comment]
I'm closing this, after concluding that the media report was mistaken. From the official gamebook, BUF has 11 QB Hits (which tallies with the NFLFastR data); they also have 5 sacks listed for them, which also matches 100% with the NFLFastR data. Whoever reported the 16 hits, probably (incorrectly) added 11 + 5 without realizing that there might be an intersection between the two. Case closed :-)

Last but not the least: Thank You folks making this resource available, you are amazing!
