### ISSUE TITLE
2020_10_DEN_LV home/away issue 

### ISSUE THREAD

**Issue by dennisbrookner** [mrcaseb/nflfastR#136]
Hey NFLfastR team,

Not sure if this has made it on y'all's radar yet, but unless we're doing something wrong, all plays from 2020_10_DEN_LV have both the home team and away team (and off team and def team) listed as Denver.  Presumably the error originates with the data source and not with the scraping, but figured I'd tell you guys regardless!

**Comment by guga31bb** [comment]
Confirmed. Tried re-scraping and same issue. Hopefully NFL will get this fixed
