### ISSUE TITLE
Negative 'end_yard_line' on kickoffs

### ISSUE THREAD

**Issue by ryjags** [mrcaseb/nflfastR#142]
There are some kickoffs, mostly with JAX kicking with Scobee or Myers, where the end_yard_line will show as a negative value. Most of the time, touchbacks register at the -5 end yard line, but there are also instances where the end_yard_line goes all the way down to the -25 end yard line in the 2013_13_JAX_CLE game.

**Comment by guga31bb** [comment]
Closing this because there's nothing we can do about it sadly
