### ISSUE TITLE
Python Wrapper / Version

### ISSUE THREAD

**Issue by kalverra** [mrcaseb/nflfastR#145]
Is there a Python wrapper or version for this library?

**Comment by mrcaseb** [comment]
The only thing I know of is [nflfastpy](https://github.com/fantasydatapros/nflfastpy). 

As far as I know it uses the [nflfastR data repo](https://github.com/guga31bb/nflfastR-data) to get the data.

**Comment by kalverra** [comment]
Perfect, thank you!
