### ISSUE TITLE
Series_result wrong on Turnovers followed by Timeouts

### ISSUE THREAD

**Issue by mrcaseb** [mrcaseb/nflfastR#149]
I am not 100% sure if it is always a Turnover followed by a Timeout or maybe also Quarter End or Game End 

    library(dplyr, warn.conflicts = FALSE)
    readRDS(url("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds")) %>% 
      filter(interception == 1, !series_result %in% c("Turnover", "Opp touchdown")) %>% 
      select(game_id, play_id, desc, series_result)
    #> # A tibble: 13 x 4
    #>    game_id     play_id desc                                      series_result  
    #>    <chr>         <dbl> <chr>                                     <chr>          
    #>  1 2020_02_CI~    3511 (11:33) 6-B.Mayfield pass deep middle in~ First down     
    #>  2 2020_02_DE~    1992 (2:09) (Shotgun) 9-J.Driskel pass short ~ Field goal     
    #>  3 2020_02_NY~    1063 (12:55) (No Huddle, Shotgun) 8-D.Jones p~ First down     
    #>  4 2020_03_DE~     560 (5:40) (No Huddle, Shotgun) 1-K.Murray p~ First down     
    #>  5 2020_03_NY~    2734 (:08) (Shotgun) 14-S.Darnold pass deep r~ First down     
    #>  6 2020_04_IN~    3731 (11:10) (Shotgun) 9-N.Foles pass deep mi~ First down     
    #>  7 2020_05_TB~     746 (3:37) (Shotgun) 9-N.Foles pass deep rig~ First down     
    #>  8 2020_08_NO~    2559 (8:41) (Shotgun) 9-N.Foles pass deep lef~ First down     
    #>  9 2020_10_MI~     343 (9:43) (Shotgun) 9-N.Foles pass deep mid~ First down     
    #> 10 2020_13_DE~    3471 (9:29) 9-M.Stafford pass short right int~ Punt           
    #> 11 2020_13_WA~    4497 (2:04) (Shotgun) 7-B.Roethlisberger pass~ Field goal     
    #> 12 2020_14_WA~    3340 (:01) (Shotgun) 4-N.Mullens pass short r~ First down     
    #> 13 2020_15_LA~    3266 (2:05) (Shotgun) 8-M.Mariota pass short ~ Missed field g~

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by guga31bb** [comment]
I think the underlying problem is actually `fixed_drive` not properly incrementing on these
