### ISSUE TITLE
Broken scores in play-by-play

### ISSUE THREAD

**Issue by mrcaseb** [mrcaseb/nflfastR#154]
The columns `total_home_score` and `total_away_score` appears to be broken in these games. Therefore Win Probability is also broken

![](https://user-images.githubusercontent.com/38586519/102888672-8b9c8180-4459-11eb-99b7-d32f243e90dc.png)

**Comment by mrcaseb** [comment]
Looks like some of them are wrong on Lee's side. Will list them below:

1. `2016_05_NE_CLE` indeed 13:33 (https://www.espn.com/nfl/game/_/gameId/400874519)
2. `2016_01_MIN_TEN` indeed 25:16 (https://www.espn.com/nfl/game/_/gameId/400874524)
3. `2015_15_KC_BAL` indeed 34:14 (https://www.espn.com/nfl/game/_/gameId/400791696)
4. `2015_09_PHI_DAL` indeed 33:27 (https://www.espn.com/nfl/game/_/gameId/400791734)
5. `2015_06_ARI_PIT` indeed 13:25 (https://www.espn.com/nfl/game/_/gameId/400791621)
6. `2013_07_CIN_DET` indeed 27:24 (https://www.espn.com/nfl/game/_/gameId/331020008)
7. `2009_17_IND_BUF` indeed 7:30 (https://www.espn.com/nfl/game/_/gameId/300103002)
8. `2006_05_STL_GB` indeed 23:20 (https://www.espn.com/nfl/game/_/gameId/261008009)



`2011_14_TB_JAX` is wrong in the pbp data. I suppose it's because of the Jags bug
`2000_11_OAK_DEN` also wrong in pbp

**Comment by mrcaseb** [comment]
Ok dived a little deeper into the two buggy games:
`2000_11_OAK_DEN` has got duplicated plays

`2011_14_TB_JAX` accounts the wrong team for the TD in `play_id == 1343`. The following Extra Point is correct

**Comment by mrcaseb** [comment]
The problem with `2011_14_TB_JAX`, `play_id == 1343` is that the TD happened on a PUNT, so the "if" condition in the below block becomes FALSE.

https://github.com/mrcaseb/nflfastR/blob/b1b290d352622e2a2ef7b290cb99449087498c17/R/helper_scrape_nfl.R#L205-L209

```
# A tibble: 1 x 4
  play_id posteam drive_how_ended_description td_team
    <dbl> <chr>   <chr>                       <chr>  
1    1343 JAC     Punt                        TB     
```

**Comment by leesharpe** [comment]
The underlying game data has been corrected in Gitbug here: https://github.com/leesharpe/nfldata/commit/828dd76a2871077b508f447a6ef79481672d3510
