### ISSUE TITLE
Unable to load multiple seasons

### ISSUE THREAD

**Issue by Rchop49** [mrcaseb/nflfastR#159]
When I try to run the command to load multiple seasons I keep getting the same error: **"Error in map(.x, .f, ...) : object 'seasons' not found"**. I also tried loading the code from the repository page but the same issue arises. I'm just learning how to code and thus new to R so this is probably just a lack of my own knowledge, but any direction would be greatly appreciated. Thank you! 

<img width="803" alt="Screen Shot 2020-12-30 at 12 58 35 PM" src="https://user-images.githubusercontent.com/68517669/103380826-df811900-4a9e-11eb-9447-9169f010e595.png">

**Comment by guga31bb** [comment]
Please make sure you define this `seasons` object with the season you want

![image](https://user-images.githubusercontent.com/1425357/103383426-af4a7200-4ac0-11eb-8149-267e4d5e5e7e.png)
