### ISSUE TITLE
Error with fast_scraper_roster - team IDs not being recognized

### ISSUE THREAD

**Issue by samhoppen** [mrcaseb/nflfastR#16]
I tried using the fast_scraper_roster function for 2019 using the team_id value in the teams_colors_logos data frame, but kept getting an error that those team IDs were not recognized. 

Here's the code that I used in trying to pull it:
![nflfastR](https://user-images.githubusercontent.com/59623962/84401714-35f13d80-abc9-11ea-9b1a-74b65c2e35d0.jpg)

And here's the error that I received:
![Error](https://user-images.githubusercontent.com/59623962/84401722-37bb0100-abc9-11ea-8d2a-5494f73505a8.jpg)

I tried with different years and still got the same issue.

**Comment by guga31bb** [comment]
This is probably because NFL took down the old feeds- theres currently no
way to get rosters and this function will be removed when we update the
package

**Comment by samhoppen** [comment]
Ahh gotcha. Damn you, NFL. Thanks for the quick response, Ben!
