### ISSUE TITLE
Do package::function for all vignettes

### ISSUE THREAD

**Issue by mrcaseb** [mrcaseb/nflfastR#168]
If we explicitly do package::function, e.g. dplyr::select() than downlit will highlight and hyperlink the functions. This helps understanding the code.

**Comment by mrcaseb** [comment]
Done for nflfastR.Rmd in https://github.com/mrcaseb/nflfastR/commit/c007c6b4ca77b2ace0a0d8bc67404bd2b2e6c29a

**Comment by guga31bb** [comment]
If we add this to the Beginner's Guide will the page display with the package:: part? 

If so I don't think we should put it in that one since it would be needlessly confusing for beginners

**Comment by mrcaseb** [comment]
That's a good point and yes it would be shown as `pkg::fct`. 
The only reason why I did this at all is that all functions will be highlighted and hyperlinked so one can click on them and will be redirected to the function documentation. 
I have no strong take if this is helpful or not for beginners so I am also ok with keeping those away from the beginner's guide.
