### ISSUE TITLE
Play Action 

### ISSUE THREAD

**Issue by norris13** [mrcaseb/nflfastR#17]
I hope this is an acceptable place to post this question, but are you aware of any data sets that may have information on whether a given play included play action?  I have spent a bit of time searching myself and am yet to find one, but that would be a fantastic addition to the data. Additionally, I know that I am not alone when I say people would help crowdfund the cost of a better data source that would have information like play action.

**Comment by guga31bb** [comment]
Unfortunately there's no public data source- one has to pay for PFF, SIS, or Sport Radar. But even paying for access doesn't give a license to publish the data, so realistically it will not be included in the data here (though I agree that it would be very useful)
