### ISSUE TITLE
Change of possession at the quarter

### ISSUE THREAD

**Issue by ConnerEvans** [mrcaseb/nflfastR#182]
I think the calculation of ep and epa is wrong when there is a change in possession at the end of the quarter. In this instance NO punted the ball to CAR at the end of the quarter but the possession team doesn't change until after the END OF QUARTER row which affects the ep and epa.

library(tidyverse)
pbp <- readRDS(url(glue::glue("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds")))
pbp %>% filter(game_id == '2020_17_NO_CAR', between(play_id, 920, 990)) %>% select(posteam, down, ydstogo, desc, ep, epa) %>% View
<img width="738" alt="Screen Shot 2021-02-10 at 9 25 04 PM" src="https://user-images.githubusercontent.com/46307733/107604940-83093180-6be6-11eb-9c09-639f24583e32.png">

**Comment by ConnerEvans** [comment]
I think the epa of row 2 should be 0 and the epa of row 1 should be (-2.419) - (-1.943) = -0.476

**Comment by guga31bb** [comment]
Good catch thank you!
