### ISSUE TITLE
More swings in WP

### ISSUE THREAD

**Issue by dhouston890** [mrcaseb/nflfastR#19]
![download (41)](https://user-images.githubusercontent.com/45542558/85206102-4ac68300-b2e5-11ea-8c7e-def0c715d3c2.png)

Hey guys, it's Daniel. I'm still seeing a few pretty dramatic swings in WP that don't seem to fit. Here's an example from the Super Bowl at the end of the 2016-17 season. To my eye, it may be that there are some plays where away vegas WP is being used instead of home vegas WP. Hope that helps!

**Comment by guga31bb** [comment]
Thanks! This is a similar issue to https://github.com/mrcaseb/nflfastR/issues/18 (PAT or kickoff with penalty messing things up) and while I fixed the problem with EP, I didn't with WP

**Comment by guga31bb** [comment]
Link for reference https://rbsdm.com/stats/box_scores/?_inputs_&type=%22post%22&away=%22NE%22&home=%22ATL%22&year=%222016%22

**Comment by guga31bb** [comment]
Fixed!
![image](https://user-images.githubusercontent.com/1425357/85208428-7144e800-b2fe-11ea-91e4-c494b2c30563.png)
