### ISSUE TITLE
Wrong posteam on kickoffs with penalties

### ISSUE THREAD

**Issue by ConnerEvans** [mrcaseb/nflfastR#199]
The posteam of line 3 in the photo below should be JAX since they were the receiving team when the penalty was incurred. Because of this, the epa in line 3 should be (0.02529127) - (0.09028234) = -0.06499107 instead of 
-(0.02529127) - (0.09028234) = -0.11557361

``` r
library(tidyverse)
pbp <- readRDS(url(glue::glue("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2017.rds")))
pbp %>% filter(game_id == '2017_12_JAX_ARI', between(play_id, 4550, 4700)) %>% select(posteam, down, ydstogo, desc, ep, epa) %>% View
```
<img width="748" alt="Screen Shot 2021-02-25 at 10 49 22 PM" src="https://user-images.githubusercontent.com/46307733/109265688-c99c8580-77bb-11eb-9678-3347b03d14a9.png">

I'm pretty sure this is the same bug, there is a penalty during a kickoff but the posteam doesn't change for the line where the penalty was incurred causing the epa to be -2*(the ep of the kickoff). 

``` r
library(tidyverse)
pbp <- readRDS(url(glue::glue("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2018.rds")))
pbp %>% filter(game_id == '2018_07_NE_CHI', between(play_id, 1450, 1550)) %>% select(posteam, down, ydstogo, desc, ep, epa) %>% View
```

<img width="733" alt="Screen Shot 2021-02-25 at 11 05 38 PM" src="https://user-images.githubusercontent.com/46307733/109267219-11bca780-77be-11eb-9b7e-50c6c5aa57a7.png">

So it seems like the posteam has a bug where it says it is the kicking team if there is a penalty when it should be the receiving team. This in turn affects the epa.

**Comment by ConnerEvans** [comment]
I just realized that I think the only penalty that causes this bug is 'delay of game'. You might want to use str_detect(desc,"Delay of Game") in the fix.

**Comment by guga31bb** [comment]
In the most recent example, the problem is that `posteam` needs to be flipped since it's a kickoff, but there's no indicators for `posteam` so it's hard to do this programmatically. I'm not sure if there's a way to fix this other than hard coding a list of plays with wrong `posteam` on kickoffs with penalty.

**Comment by ConnerEvans** [comment]
I just ran the code below today: 3/7/21 9:30am PST and verified that there is still one more instance of this happening in the current data because it was a different penalty (Unnecessary Roughness).

```r
pbp <- nflfastR::load_pbp(2011:2020, qs = TRUE)

pbp %>% filter(game_id == '2014_02_ATL_CIN', between(play_id, 3450, 3600)) %>% select(home_team, away_team, posteam, desc, ep, epa) %>% View
```

<img width="793" alt="Screen Shot 2021-03-07 at 9 34 58 AM" src="https://user-images.githubusercontent.com/46307733/110248947-6c75a200-7f28-11eb-95f2-aca75b05497b.png">


This is how I'm currently hardcoding a fix:
```r
epapp_game <- pbp %>%
  filter(!is.na(posteam),!is.na(ep),quarter_end==0) %>%
  group_by(game_id,game_half) %>%
  
  mutate(
    epa = if_else(is.na(epa), -ep, epa),
    
    posteam = if_else((game_id == '2014_02_ATL_CIN')&(play_id==3498),home_team,posteam),
    kickoff_attempt = if_else((game_id == '2014_02_ATL_CIN')&(play_id==3498),1,kickoff_attempt),
    epa = if_else((game_id == '2014_02_ATL_CIN')&(play_id==3498),lead(ep)-ep,epa),
  )
```
