### ISSUE TITLE
Player Names

### ISSUE THREAD

**Issue by haydenwinks** [mrcaseb/nflfastR#20]
There are a handful of players with two different names...
+ M.Ingram and M.Ingram II
+ D.Chark and D.Chark Jr.
+ G.Minshew and G.Minshew Jr.
+ O.Beckham and O.Beckham Jr.
+ D.Johnson and D.Johnson Jr. (that's Duke Johnson, not David Johnson)
+ A.Robinson and A.Robinson II

**Comment by guga31bb** [comment]
Which variable are you looking at? Would you be able to provide a code snippet? Thanks!

**Comment by mrcaseb** [comment]
In which variables are you finding those?

**Comment by mrcaseb** [comment]
Oh sorry Ben was a few seconds faster...

**Comment by tomdicato** [comment]
I found one for Mark Ingram in rusher_player_name specifically in 2019.

readRDS(
  url(
    "https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2019.rds"
  )
) %>%
  filter(str_detect(rusher_player_name, "Ingram")) %>%
  distinct(rusher_player_name)

**Comment by guga31bb** [comment]
Please replace `rusher` with `rusher_player_name`, and there won't be dups. Please [see this section](https://github.com/guga31bb/nflfastR-data/blob/master/man/beginners_guide.md#group-by-and-summarize) discussing names and [this section](https://github.com/guga31bb/nflfastR-data/blob/master/man/beginners_guide.md#figures-with-qb-stats) on unique name +ID combos.

In short, use `passer`, `rusher`, or `receiver` for names, not the `XX_player_name` variables which are the ones provided with NFL and can change over time
