### ISSUE TITLE
tackle_with_assist_1_team bug

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#206]
The variable tackle_with_assist_1_team (and I assume tackle_with_assist_2_team) are using the old franchise designation of "OAK" instead of "LV" like the other tackle variables. It's throwing off team-level tackle counts for me. I noticed it on

2641 | 2018_09_OAK_SF and 2986 | 2018_10_LAC_OAK

**Comment by mrcaseb** [comment]
Good catch. I forgot to add the variable to the below given block. 

https://github.com/mrcaseb/nflfastR/blob/4dc670e91b12634ba34a58fa13b8671549f865fb/R/helper_additional_functions.R#L170-L177
