### ISSUE TITLE
Safety Points go to DAL not JAX in 2014_10_DAL_JAX

### ISSUE THREAD

**Issue by ConnerEvans** [mrcaseb/nflfastR#209]
I have attached a screenshot of the output from the code below and of the game as its shown on ESPN. The safety shown in line 3 of the output adds two points to DAL when the text description and other sources say that JAX got the safety.

```r
pbp %>% filter(game_id == '2014_10_DAL_JAX', between(play_id, 3250, 3350)) %>% select(posteam, desc, ep, epa, total_home_score, total_away_score) %>% View
```
<img width="846" alt="Screen Shot 2021-03-06 at 10 18 37 AM" src="https://user-images.githubusercontent.com/46307733/110216831-1b9d7500-7e66-11eb-87e3-4a84a79b8a0f.png">

<img width="1440" alt="Screen Shot 2021-03-06 at 10 18 58 AM" src="https://user-images.githubusercontent.com/46307733/110216826-15a79400-7e66-11eb-82f3-3ac5f636474b.png">

**Comment by ConnerEvans** [comment]
The link for the ESPN page is https://www.espn.com/nfl/game?gameId=400554358

**Comment by mrcaseb** [comment]
This is weird as we had fixed all score problems in #154. This must be introduced with the latest posteam changes.

**Comment by TheMathNinja** [comment]
Whoa does this mean that team designations had been fixed at one point for fumble recoverer, interceptor, sacker, etc. in the JAX games from 2011-2015? Or is that a separate issue? Because I have been treating this issue as intractable in my code for the last year.

**Comment by ConnerEvans** [comment]
Last one from what I can tell:

```r
pbp %>% filter(game_id == '2013_01_KC_JAX', between(play_id, 230, 330)) %>% select(home_team, away_team, posteam, desc, ep, epa, total_home_score, total_away_score) %>% View
```

<img width="940" alt="Screen Shot 2021-03-07 at 9 25 27 AM" src="https://user-images.githubusercontent.com/46307733/110248692-400d5600-7f27-11eb-9d93-0d0612b5145c.png">

https://www.espn.com/nfl/game?gameId=330908030

<img width="993" alt="Screen Shot 2021-03-07 at 9 25 55 AM" src="https://user-images.githubusercontent.com/46307733/110248700-4a2f5480-7f27-11eb-91f0-535700622315.png">

**Comment by guga31bb** [comment]
```
get_season <- function(s) {
  
  nflfastR::load_pbp(s) %>%
    group_by(game_id) %>%
    summarise(
      home_pbp = max(total_home_score),
      home_lee = max(home_score),
      away_pbp = max(total_away_score),
      away_lee = max(away_score)
    ) %>%
    filter(
      !(home_pbp == home_lee & away_pbp == away_lee)
    ) %>%
    ungroup() %>%
    return()
  
}

bad_games <- map_df(1999 : 2020, ~{get_season(.x)})

> bad_games
# A tibble: 15 x 5
   game_id         home_pbp home_lee away_pbp away_lee
   <chr>              <dbl>    <int>    <dbl>    <int>
 1 2000_11_OAK_DEN       24       27       36       24
 2 2001_09_CIN_JAX       28       30       15       13
 3 2001_16_KC_JAX        24       26       32       30
 4 2002_08_HOU_JAX       17       19       23       21
 5 2004_11_TEN_JAX       13       15       20       18
 6 2004_14_CHI_JAX       20       22        5        3
 7 2006_14_IND_JAX       38       44       23       17
 8 2007_17_JAX_HOU       30       42       40       28
 9 2008_09_JAX_CIN       27       21       13       19
10 2008_12_MIN_JAX       10       12       32       30
11 2009_15_IND_JAX       37       31       29       35
12 2010_15_JAX_IND       28       34       30       24
13 2013_01_KC_JAX         0        2       30       28
14 2014_10_DAL_JAX       15       17       33       31
15 2015_15_KC_BAL        14       14       34       38
```
Looks like a bunch of Jags games being messed up
