### ISSUE TITLE
Problem with return touchdowns

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#21]
I've found a large class of plays in which there were touchdown==1 but where pass_touchdown, rush_touchdown, and return_touchdown are all =0. These all seem to be fumble return TD's, and it seems to me they should be scored as return_touchdown = 1. 

Examples include:
game_id 2019_03_NO_SEA, play_id 1399
game_id 2019_04_KC_DET, play_id 2657
game_id 2019_04_TB_LA, play_id 5000

**Comment by guga31bb** [comment]
touchdown = 1 on these plays is expected behavior because a touchdown was
scored.

In practice, I usually detect offensive TDs with touchdown == 1 & td_team
== posteam.

I'll leave this open for now because maybe we should add a score_type
column or something

**Comment by TheMathNinja** [comment]
I think touchdown == 1 is the right call here.

My question is this: why are you scoring INT touchdowns as return_touchdown == 1, but Fumble Recovery touchdowns are return_touchdown == 0? Shouldn't fumble recovery touchdowns be return_touchdown == 1 also?

**Comment by TheMathNinja** [comment]
Or in other words, aren’t the following functions supposed to be related in this way?:
rush_touchdown + pass_touchdown + return_touchdown = touchdown?

**Comment by guga31bb** [comment]
Yep this was a bug and has been fixed, which will be updated when we re-scrape (going to look at some of these other issues before doing that). Thanks!
