### ISSUE TITLE
update_db disconnects odbc connection

### ISSUE THREAD

**Issue by bkmontgom** [mrcaseb/nflfastR#210]
I have a local PostGreSQL database that I connect to with ODBC.  When I run update_db, it disconnects and dbGetQuery throws an error.  It's easy to fix by reconnecting (commented out lines), but still annoying.
Similar to #102 
Version 4.0.0.9002

```r
library(nflfastR)
library(odbc)

con <- dbConnect(odbc(), 'PostGreSQL30 - nflfastR')
update_db(db_connection = con, tblname = 'nflfastr_pbp')
# update_db disconnects the database, so need to reconnect
# con <- dbConnect(odbc(), 'PostGreSQL30 - nflfastR')
pbp <- dbGetQuery(con, "SELECT * FROM nflfastr_pbp where season = 2020")
```

**Comment by mrcaseb** [comment]
Wow that's pretty stupid. I don't understand why nobody called me out for that earlier. 

It's easy to fix but I need to check if it can break people's scripts of they worked around it by reconnecting after `update_db()` disconnected. 

Thanks for pointing this out @bkmontgom !
