### ISSUE TITLE
In 2020_01_TB_NO, the Muffed KO is Treated as a Possession/Drive and a Red Zone Drive

### ISSUE THREAD

**Issue by JoeMarino2021** [mrcaseb/nflfastR#217]
In 2020_01_TB_NO, the following fourth quarter play (PID = 3509?) is treated as a possession/drive and a red zone drive for TB.

6-T.Morstead kicks 33 yards from 50 to TB 17. 32-M.Edwards MUFFS catch, RECOVERED by NO-16-B.Fowler at TB 18. 16-B.Fowler to TB 18 for no gain (17-J.Watson).

If the desire is to match up with official accounts, then NO is credited with two consecutive drives/possessions here (NO and TB each officially have 13 drives for the game, so 26 total drives in the game).  Depending on your analysis, it is possible that counting this as a TB "drive" may be more accurate.  My personal preference would be to not increment the drive counter here.

What is probably not desired by nflfastR or any analyst's purpose, however, is the setting of the red zone flag (drive_inside20) on this pseudodrive to 1.  TB certainly did not advance the ball into the red zone on this possession.  That flag variable should be 0 here.

Thanks for the great tool, and thanks for reading this report.  Have an incredible day!

**Comment by JoeMarino2021** [comment]
So, let me get this straight so I know how to code it on my end.  For the following play:

play_id | game_id | yards_gained | fixed_drive | posteam | play_type | extra_point_attempt | desc
3509 | 2020_01_TB_NO | 0 | 21 | TB | kickoff | 0 | 6-T.Morstead kicks 33 yards from 50 to TB 17. 32-M.Edwards MUFFS catch, RECOVERED by NO-16-B.Fowler at TB 18. 16-B.Fowler to TB 18 for no gain (17-J.Watson).

The posteam will remain TB, but the fixed_drive will not increment to 21?  So, the total drives in the game will be 26?  Two teams will be shown as the posteam for drive 20?

**Comment by guga31bb** [comment]
`fixed_drive` will increment to 21 once we fix it and there will be 26 drives

> Two teams will be shown as the posteam for drive 20?

For drive 21, yes. I typically deal with this by throwing away plays with `NA` down when counting drives by team

**Comment by JoeMarino2021** [comment]
This becomes the start of drive 21 for NO, with the first play listed as belonging to TB?  So, the drive 22, which belonged to NO entirely will now be drive 21, shared with TB?
