### ISSUE TITLE
2020_10_DEN_LV PID: 979 Successful Fourth Down Conversion on Play with a Holding

### ISSUE THREAD

**Issue by JoeMarino2021** [mrcaseb/nflfastR#218]
On the first play of the second quarter Vegas lined up to try a 4th and 1 from Denver's 30.

PID QTR SIT                     DESC
979 2     LV-4-1-DEN 30 (15:00) J.Jacobs right guard to DEN 29 for 1 yard (B.Chubb). PENALTY on LV-B.Parker, Offensive Holding, 10 yards, enforced at DEN 30 - No Play.

This play has the "fourth_down_converted" flag set to 1.  It should be set to 0.  Vegas would go on to punt on the subsequent 4th and 11 after their holding.

Thanks again for everything!  Keep up the tremendous work!

**Comment by JoeMarino2021** [comment]
Instead of hard coding this play to correct it (which would allow for the root cause to create the error again), would it not be better to note that the following play was also a fourth down?  Also, if a 4th down is successful, shouldn't a TD be scored or a first down earned?  Looking at the play description for a "TOUCHDOWN" or at the next play for a first down should better resolve this issue, no?

Thanks for all of the quick work on these issues!

**Comment by mrcaseb** [comment]
The root cause of the problem are the score keepers of the NFL. It's in the underlying data. There is nothing we can do to prevent this. It simply shouldn't happen on the NFL's part.

**Comment by JoeMarino2021** [comment]
Oh.  OK.  So if the nflfastR code will work on correct NFL data, then never mind.  We can only hope for the NFL to get it right in the future.  We can't do their job for them.

Thanks.
