### ISSUE TITLE
Special definition for pass attempt?

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#24]
Sorry if this does not qualify as an "issue" (I'm still a bit new to github), but I was noticing that sacks are scored as pass_attempt in this data set, where the NFL does not score sacks as pass attempts in its guide for statisticians. Just wanted to make sure this choice to define pass attempts differently than the NFL was purposeful; I can see the logic in it, but thought it might create confusing results for people new to the package, and might require more explanation than is desired.

**Comment by guga31bb** [comment]
If you aren't about whether something is an issue, please leave as an issue and we can decide- we want to know about anything that doesn't look right!

On this one, `pass_attempt` is a variable inherited from `nflscrapR`, and in [their definition](https://www.rdocumentation.org/packages/nflscrapR/versions/1.8.1/topics/scrape_json_play_by_play), they include sacks:

>pass_attempt - Binary indicator for if the play was a pass attempt (includes sacks).

So I don't think we should change it, although I agree it's confusing.
