### ISSUE TITLE
Onside Kick Win Prob

### ISSUE THREAD

**Issue by ajreinhard** [mrcaseb/nflfastR#25]
It looks like win probability might be reversed in some onside kick situations. I can't imagine why this might be, but below is the query that I used to identify maybe 15 examples.

In making this query, I also noticed that there is at least one play where the game appears to end on a kickoff and return a strange final value. (game_id == '2019_18_TEN_NE' & play_id == 3865) should have a wpa of -0.011, as the Patriots (receiving team and posteam) had a 1.1% chance to win prior to the kick, which was the game's final play.

```
pbp_df <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2019.rds'))

pbp_df %>% 
  filter(play_type=='kickoff' | grepl('onside', desc, ignore.case = T)) %>% 
  mutate(onside = ifelse(grepl('onside', desc, ignore.case = T), 1, 0)) %>% 
  select(game_id, play_type, play_id, game_seconds_remaining, wpa, wp, vegas_wp, onside, own_kickoff_recovery, desc) %>% 
  arrange(-abs(wpa)) %>%
  View
```

**Comment by guga31bb** [comment]
This was caused by me attempting to fix PATs with penalties by looking for "Kick formation" in the description. But this also caught onsides kicks and made them the wrong possession team. This has been fixed and will be updated once we update the package / rescrape the data. Thank you and good catch!

**Comment by ajreinhard** [comment]
Awesome work Ben, thanks for looking into all of these. I'll let you know if I continue to see weird stuff on PATs/kickoffs
