### ISSUE TITLE
Positive EPA on failed 3rd downs

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#30]
This could just be a feature of the model as it stands, but I'm finding it strange that quite a few failed 3rd down plays with 0 yards gained are returning positive (and substantially positive) EPA values. This is true for the following 6 plays, all with EPA between 0.2 and 0.6 for failed third down attempts:

play_id | game_id
2178 | 2015_15_HOU_IND
3855 | 2014_07_NYG_DAL
3948 | 2014_12_CIN_HOU
3901 | 2015_02_NYJ_IND
3684 | 2018_03_CIN_CAR
3467 | 2019_09_GB_LAC

**Comment by TheMathNinja** [comment]
I'll add these as a similar anomaly. Here are 4 plays in which an incomplete pass produced EPA of 1.4-2.2. That strikes me as a larger issue than the one above. Looks like it could be related to creating a 2018-2019 bin for EPA since they are all in that range?
play_id | game_id
-- | --
3832 | 2019_09_IND_PIT
3001 | 2019_05_MIN_NYG
988 | 2019_02_SEA_PIT
811 | 2018_05_MIA_CIN

**Comment by guga31bb** [comment]
Good catch. These aren't problems with the EP model itself but rather an issue caused by failed challenge. Each of these 4 plays was the play directly before a failed challenge.

**Comment by guga31bb** [comment]
The one in the first comment is due to how the EP model treats field goal attempts, which makes EP "too high" on these 4th downs.

I never understood why nflscrapR treated field goals as a special case in the EP model but we just followed what they did, for better or worse.

But the failed challenge thing needs fixing!

**Comment by guga31bb** [comment]
The 4 plays with very high EPA have been fixed and will be updated next time I update the data repo- thank you!

The other one isn't really an "error" as much as the EPA calculation being weird on some field goals. Maybe this should be changed but I'd prefer to diverge from nflscrapR as little as possible. As always, thank you!

**Comment by guga31bb** [comment]
Leaving this comment here even though it's relevant to a lot of recently-closed issues, but the data repo has been updated
