### ISSUE TITLE
Another WP issue

### ISSUE THREAD

**Issue by dhouston890** [mrcaseb/nflfastR#31]
Found another possible WP issue similar to Issue #19. This is for the Cowboys-Ravens regular season game in 2016. Appears away_wp value may be showing up in home_wp for one of these rows. Chart: https://twitter.com/NotToBeTrite/status/1278004814656475145

**Comment by dhouston890** [comment]
Found one more example of this from MIA @ DAL game in 2019 regular season.

<img width="912" alt="Screen Shot 2020-06-30 at 1 13 47 PM" src="https://user-images.githubusercontent.com/45542558/86162099-e5884400-bad3-11ea-9619-883c8fa73a08.png">

**Comment by guga31bb** [comment]
Just stop committing penalties on kickoffs, is that too much to ask,,,,

![image](https://user-images.githubusercontent.com/1425357/86166161-53d40300-bae2-11ea-89ee-ef51fd710cd0.png)

**Comment by guga31bb** [comment]
This has been fixed in our development branch so will be fixed next update. Thanks again!

**Comment by guga31bb** [comment]
Updated! 

https://rbsdm.com/stats/box_scores/?_inputs_&type=%22reg%22&away=%22MIA%22&home=%22DAL%22&year=%222019%22 
![image](https://user-images.githubusercontent.com/1425357/86519020-9b210300-be04-11ea-9424-438473769992.png)
