### ISSUE TITLE
First Down bug in one game

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#32]
I'm getting a weird under-reporting of first downs in one particular game:

game_id 2018_01_ATL_PHI, play_id 4024 is a 21-yard run on 3rd & 2 but shows no First Down.
game_id 2018_01_ATL_PHI, play_id 125 is a 20 yard run on 1st & 10 but shows no First Down. 
game_id 2018_01_ATL_PHI, play_id 3460 is a 16 yard run on 3rd & 1 but no First Down.

**Comment by guga31bb** [comment]
This is another NFL data issue (the stat IDs indicating first downs aren't present in these plays) but since it's only 3 plays it will be easy for us to manually fix. Thanks!

**Comment by TheMathNinja** [comment]
Just to be clear, these 3 stuck out to me at the head of a data set, but I have not actually checked to see how many plays in this game might be affected by this first down bug.

**Comment by TheMathNinja** [comment]
On closer inspection, it looks like a problem with the whole game. I'm seeing the problem on all of these plays in that game:

104
125
190
445
492
752
1037
1085
1160
1423
1869
2284
2450
2672
2736
2811
3460
3507
3950
4024
4166
4258
4325

**Comment by guga31bb** [comment]
Thank you! This will be fixed in the next release
