### ISSUE TITLE
Calculate_expected_points broken in example

### ISSUE THREAD

**Issue by Maecenas49** [mrcaseb/nflfastR#34]
Running through the examples vignette and get this error when attempting to calculate expected points:
``nflfastR::calculate_expected_points(data)# %>%
  select(season, yardline_100, td_prob, ep) %>% 
  knitr::kable(digits = 2)``

``Error: Problem with `mutate()` input `model_week`. x object 'week' not found i Input `model_week` is `dplyr::if_else(week > 17, as.integer(17), as.integer(week))`.``

**Comment by mrcaseb** [comment]
Looks like you are trying an example which is written for nflfastR v2.1.0 with an older version. The latest update removed `week` from the models. Please update nflfastR and it should work.

**Comment by Maecenas49** [comment]
That was it. Thank you
