### ISSUE TITLE
Second fumble not reported

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#38]
Looking at game_id 2015_12_BUF_KC, play_id 4100, I see 2 fumbles on the play by Tyrod Taylor, but I notice the fumbled_2_player_id, fumbled_2_player_name, and fumbled_2_team variables are all NA. Is this a bug or is something on the NFL's end?

**Comment by TheMathNinja** [comment]
I'm getting this same result on game_id 2018_15_PHI_LA, play_id 2933 and game_id 2014_02_HOU_OAK, play_id 1794.

In both plays, a player fumbles twice but nobody is listed as the second fumbling team or player. These plays show a recovery player and team of "fumble 2" but nobody fumbling for "fumble 2".

**Comment by TheMathNinja** [comment]
I suppose this request is a request for a slight change in the definition of the variables themselves. I'm not entirely sure what is meant by:
fumbled_2_player_id Unique identifier of one of the players with a fumble.
fumbled_2_player_name String name of one of the players with a fumble.
fumbled_2_team Team of one of the players with a fumble.
But it seems like this is identifying any second unique player on the play who fumbles on the play, rather than who fumbled the second chronological fumble.

But I'm wondering if we could change the meaning of this variable to be:
fumbled_2_player_id Unique identifier of the player responsible for the second fumble on the play.
fumbled_2_player_name String name of the player responsible for the second fumble on the play.
fumbled_2_team Team of the player responsible for the second fumble on the play.

Otherwise it's very difficult to identify plays in which a single player fumbles twice on the same play. Under this schema, it might be necessary to include fumbled_3 variables. I can't quite tell if there are any plays in the dataset with 3 fumbles on the same play because of how these variables are defined (also, there is a "fumble" binary variable but not a "fumbles" variable, which might be helpful).

**Comment by guga31bb** [comment]
Made the documentation more clear about what this means: "Unique identifier of the first player who fumbled on the play."

**Comment by TheMathNinja** [comment]
Does this mean there's no way from the data to create the second kind of variables?:

fumbled_2_player_id Unique identifier of the player responsible for the second fumble on the play.
fumbled_2_player_name String name of the player responsible for the second fumble on the play.
fumbled_2_team Team of the player responsible for the second fumble on the play.
