### ISSUE TITLE
New aborted_snap function?

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#39]
I was wondering if we could get an nflfastR aborted_snap function included in the data set? This variable would need to be scraped, I believe, but seems fairly straightforward, as in every case I believe the desc includes the word "aborted"

**Comment by guga31bb** [comment]
Was actually thinking about this too because it would make excluding these plays easier. Putting this on the to-do list

**Comment by TheMathNinja** [comment]
On closer inspection, this should be called "aborted_play" not aborted_snap. That's what the NFL officially calls it, and as you showed via your Darnold tweet, aborted plays may not involve a bad snap at all.

**Comment by guga31bb** [comment]
Closing this as we've added `aborted_play` for the next version. Thanks!
