### ISSUE TITLE
Zero EP/EPA on wrong play

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#42]
I'm noticing on game_id 2017_02_NE_NO, play_id 3574 that there is a 0 listed EP and EPA, where seems to me the play should have non-zero values for both. It was a costly 6 yard penalty play in a high-EP scenario.

I'm noticing the same bug in the following plays:
2017_03_CIN_GB | 2653
2017_13_KC_NYJ | 926
2018_16_KC_SEA | 1586
2015_15_HOU_IND | 2201

I was specifically looking at plays which were timeout/no_play/penalty plays, and the vast majority of them have EPA assigned. Just these ones did not. I can't quite figure out why.

**Comment by guga31bb** [comment]
More bugs on failed challenges, just made a fix that will appear in the next version. Thanks!
