### ISSUE TITLE
Timeout variable confusion

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#43]
I'm noticing that in the case of TV timeouts, the timeout variable is NA. Looks like on these plays, play_type is NA and play_type_nfl is TIMEOUT. 

It seems to me there should be some way of indicating a TV timeout. Either:
1. Changing the timeout variable to include these, or 
2. Perhaps re-defining the timeout variable in the logs as from "Binary indicator for whether or not a timeout was called" to "Binary indicator for whether or not a timeout was called by either team."

**Comment by guga31bb** [comment]
Good suggestion and going with #2. Thanks!
