### ISSUE TITLE
Formation variable

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#45]
Working through some special plays, I'm realizing a formation variable could be helpful. Trying to study offensive penalties and I'm struggling to filter out this play: 1943 | 2017_14_NO_ATL. It seems like we can't quite get positional data in at the moment, but I know this play starts with "Field Goal formation" so I'm wondering if making a formation variable could filter out "Field Goal formation" and "Punt formation" kinds of plays. It seems like the most common words to show up here are "Punt" "Run" "Pass" "Shotgun" and "Field Goal". Maybe those could be the variable types?

**Comment by TheMathNinja** [comment]
On second thought, this "formation" data is so spotty. I think it would actually be better on no_plays to analyze words in the desc that aren't linked to formation. This play contains the word "field goal," others will have "punts," "run," "pass," etc. Ultimately, what I'm hoping for/wanting is a play_type variable which still shows the play type / intent even if there is no_play. More of a robust play_type variable.

**Comment by guga31bb** [comment]
I've looked into this before but there are so many plays where you can't tell intent that it seemed to be not feasible. Going to close this since I don't think it's actionable.
