### ISSUE TITLE
Faulty no_play designation

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#46]
I'm noticing there is a large body of plays in which there is a pass attempt and a penalty which is assessed at the end of the play, but it's getting coded as play_type == no_play instead of as a pass play. 

Using the filter:
play_type == "no_play" & pass_attempt == 1 
will show this body of plays. It's looking like there might be something a bit off in how "no_play" is determined. This appears to be an issue of some "no_play" designations needing to become "play_type == pass". I see no examples of a false no_play on rush attempts.

**Comment by guga31bb** [comment]
Yep someone raised this on twitter so thanks for filing this here. Pretty sure this is another inherited bug from nflfscrapr

**Comment by TheMathNinja** [comment]
I'm noticing a new class of plays on which this is an issue. Plays like 2955 | 2019_01_HOU_NO are converted Extra Points which are being classified as no_play by this same bug. I'm now realizing that this bug is also affecting two point conversion attempts and this is the same bug causing issue #49. In the case of the 2PC's causing NA values for EPA, but in the case of the Extra Points, it seems to be skipping over plays for EPA.

**Comment by guga31bb** [comment]
Fixed for the next version for data 2011 and onward by using `play_type_nfl` when available. Thank you!
