### ISSUE TITLE
Handling multiple penalties

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#47]
Looking at this play:  play 1542 | 2017_07_KC_OAK  exposes a couple problems in handling plays with multiple accepted penalties.

There is an accepted penalty on both offense and defense here. 14 yards unnecessary roughness on the D, and 15 yard penalty with disqualification on offense. However, there's only one variable for penalty_player and penalty_team and penalty_yards, so they put them all on the offense. Oddly, penalty_type takes on the defensive penalty here (I'm not sure an offensive penalty type is listed?). Anyway, this leads to the odd result of showing a 15 yard offensive penalty adding 0.59 EPA.

Is it possible to have a penalty_player_1 and penalty_player_2 setup? As well as penalty_team_1 and penalty_team_2 and penalty_yards_1 and penalty_yards_2 variables to handle this kind of situation?

**Comment by vita10gy** [comment]
I do nflpenalties.com, a quick and dirty query (so don't bet your house on these numbers) shows these per-play counts for accepted penalties. (Declined/Offsetting goes up to 6.)
  
penalty_per_play	instances
1	37541
2	337
3	17
4	1

So 2 is rarish and 3 pretty out there, but if you're going to do _2 you may as well do _3, right? I wonder how rare some of the other _2 _3 fields are used in comparison.

This is one of those "perils of a flat file" things.

**Comment by vita10gy** [comment]
For fun, here's the 4 - 2017 week 13 NE @ BUF

Here's the 4
4:50) (Shotgun) T.Brady pass deep right intended for R.Gronkowski INTERCEPTED by T.White at BUF 41. T.White to BUF 41 for no gain (P.Dorsett). BUF-T.White was injured during the play.  Penalty on NE-R.Gronkowski, Unnecessary Roughness, offsetting. Penalty on NE-D.Amendola, Unnecessary Roughness, offsetting. Penalty on BUF-M.Hyde, Unnecessary Roughness, offsetting. PENALTY on BUF-J.Hughes, Unsportsmanlike Conduct, 15 yards, enforced between downs. Unsportmanlike conduct foul against an official, penalty assessed after chains set, results in 1st-and-25 for BUF.

**Comment by guga31bb** [comment]
Just checked and the EPA part is correct
