### ISSUE TITLE
Update to two point conversion EP & probabilities

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#48]
I'm noticing that Extra Point EP will change with various game scenarios including what yard line the extra point is being kicked from, but that there are no changes for two point conversions. I'm wondering if perhaps the sample size is now significant enough that two point conversion probabilities might be updated based upon yard line at least (if not some other factors which are considered for extra points)

**Comment by guga31bb** [comment]
We can do this with extra points because we have the full sample of field goals to draw upon to estimate the probability of a made kick at various distances. But for 2-point conversions, sample sizes are really small. Maybe there are enough to do attempts from the 1-2 yard lines.

**Comment by TheMathNinja** [comment]
If you're willing to use the FG data for XP's, it seems like the same logic could lead you to use any 4th and Goal to estimate the 2-point conversion probabilities. I don't have an opinion without looking at it closely, just wanted to propose this if you liked it.
