### ISSUE TITLE
False NA values on Two Point Conversions

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#49]
I'm noticing that successful two point conversions which have penalties assessed on the kickoff, are being labelled as play_type == no_play and have no EP/EPA values. I suppose this might be an example of having hit the "end of the road" on EP/EPA. It seems like a short term fix could at least be to credit these as successful two point conversions and not no-plays.

Perhaps a more solid long-term solution would be to include the ensuing kickoff in the EPA calculations for point-after conversions, so that these penalties could be appropriately baked into the EPA on the conversion itself. I do realize this leads to a large rabbit hole on the method of how EPA is calculated...but I do believe this method will bring about more accurate results in the long-term.

3 examples from 2019:
3801 | 2019_06_SEA_CLE
2041 | 2019_08_PHI_BUF
2158 | 2019_13_PHI_MIA

**Comment by guga31bb** [comment]
Finally fixed this and will be updated in next version of the package. It's hard to fix these things without breaking other things so please let us know if anything else looks off. Thanks!
