### ISSUE TITLE
install script fails in R 4.0.0

### ISSUE THREAD

**Issue by pdxsanchez** [mrcaseb/nflfastR#5]
> devtools::install_github("mrcaseb/nflfastR")
Downloading GitHub repo mrcaseb/nflfastR@master
Skipping 1 packages not available: nflscrapR
Installing 3 packages: nflscrapR, janitor, snakecase
Installing packages into ‘C:/.....’
(as ‘lib’ is unspecified)
Error: Failed to install 'nflfastR' from GitHub:
  (converted from warning) package ‘nflscrapR’ is not available (for R version 4.0.0)

**Comment by guga31bb** [comment]
Thanks for the heads up. We had not tested this with 4.0!

**Comment by pdxsanchez** [comment]
FYI:  Installing ryurko/nflscrapR, (1.8.3) and then nflfastR seemed to work.  :)

**Comment by guga31bb** [comment]
Closing this at it appears to be related to needing nflscrapR installed for the installation to work (which is expected behavior)
