### ISSUE TITLE
EPA error for defensive two point conversions

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#50]
I'm noticing that EPA is reading as -0.947 on defensive two point conversion plays (defensive_two_point_conv == 1), when it should be reading -2.947. It seems like the EPA formula is registering 0 points rather than -2 on the play.

This also makes me wonder if EP on point after attempts is including the possibility of a 2 point return. Might lower the EP a slight amount.

**Comment by guga31bb** [comment]
Fixed this for next version, thanks!
