### ISSUE TITLE
Defensive Extra Point Attempts

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#51]
Just curious about why defensive extra point attempts are in the data set. These appear to be NCAA-only variables (stat_id == 405 and 406). So these are always 0 in nflfastR. If an XP is blocked in the NFL, and a return is attempted, it's logged as a defensive two-point attempt. If clearing out unnecessary variables is a priority, this could be worth it.

**Comment by guga31bb** [comment]
This exists because we originally copied columns from `nflscrapR`. I agree that it's useless but removing columns that already exist is probably a bad idea.

**Comment by TheMathNinja** [comment]
Got it. Didn't know if that would create problems or not.
