### ISSUE TITLE
Field Goal return yards and TDs

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#52]
Is there any way to get data on the length of return yards on a field goal (blocked or not)? I'm looking at field goals that were blocked and returned for TDs, and I'm not seeing the return yards or TD show up in any columns. These plays show touchdown == 1 but rush, pass, and return_touchdown variables are all 0.

**Comment by guga31bb** [comment]
Unless I'm missing something, seems like there's no stat IDs that cover field goal returns http://www.nflgsis.com/gsis/documentation/Partners/StatIDs.html
