### ISSUE TITLE
variable issues on NA/no_plays

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#55]
Seeing a couple variable issues on NA/no_play play_types (timeouts, two minute warning, end-of-quarter, etc.) plays:

1. yrdln is incorrect. I'm noticing on 2629 | 2019_01_BUF_NYJ it should read yrdln == BUF 20, but it shows BUF 24. It's reading the yardline of where the previous play started rather than ended. Pretty sure it should be reading where the previous play ended (or where the next play starts...but those should be the same).

2. end_yard_line is NA, but I think it makes sense if it's the same as yardln.

3. Tons of variables (posteam, posteam_type, defteam, side_of_field, down, timeouts_remaining, score, score differential, wp, wpa) are NA when they should generally have values. This will especially be helpful identifying situations in which timeouts are taken.

**Comment by guga31bb** [comment]
On 3, we can't fill in the values because it would break a lot of other things, especially the EPA calculations, but users can get values of the prior play using ``dplyr::lag()``

**Comment by guga31bb** [comment]
Fixed 1 since it was a bug on our end and you're right about expected behavior (will update once data repo updates). The rest will be left the same to not break other things. Thank you as always!
