### ISSUE TITLE
tackled_for_loss description

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#56]
I'm noticing that some plays have tackled_for_loss == 0 and tackle_for_loss_player_id == notNA. I'm seeing that these are taken right from the NFL GSIS (stat_id 95 and stat_id 120), so it appears to be a weird NFL issue.

Looking at stat_id 95's description in the GSIS, it appears to just be for rush plays. Negative passing plays and sacks are not getting credited, I'm noticing. Perhaps the variable should be renamed within nflfastR from "tackled_for_loss" to "team_tackled_for_loss"? In the GSIS this appears to be a team variable, which is why it's not lining up with the individual variable, I think. And the description in the nflfastR documentation could be clearer this is a team variable and only on rushes.

**Comment by guga31bb** [comment]
Changing documentation to note that this only applies to run plays- thanks!
