### ISSUE TITLE
Snap counts

### ISSUE THREAD

**Issue by jseibert575** [mrcaseb/nflfastR#57]
Not sure if this is the right place to ask this, but are snap counts for different players accessible in any way through the data provided by nflfastR? Thanks!

**Comment by guga31bb** [comment]
This is a good place to ask questions! Sadly, NFL doesn't provide data on snap counts, so we can't provide it. I personally [check snap counts using PFR, here's an example page](https://www.pro-football-reference.com/teams/crd/2019-snap-counts.htm)
