### ISSUE TITLE
Two variables (could help EPA/WPA)

### ISSUE THREAD

**Issue by TheMathNinja** [mrcaseb/nflfastR#58]
Perhaps someone has already done this work, but I wanted to suggest including two additional variables in the nflfastR dataset:

1. attendance (data going back to 1999 and further can be found at https://www.pro-football-reference.com/years/1999/attendance.htm on the various year pages).
2. elevation (looks like decent data at https://www.arcgis.com/home/webmap/viewer.html?useExisting=1&layers=eb3d7b273ed5418882be29e9b4148d46 for stadiums in 2016, but I cannot verify its accuracy)

I've seen a few studies suggesting that home-field advantage increases with attendance, and we know the impact elevation has on various elements of the game. I think including these could help increase the accuracy of the EPA and WPA models.

**Comment by TheMathNinja** [comment]
Upon further inspection, the aforementioned site for elevation is not the best. The best data is found here: https://viewer.nationalmap.gov/advanced-viewer/

This also provides precise latitude and longitude, which could be great data to include also (serving both as a proxy for weather, as well as travel distance between games).

**Comment by TheMathNinja** [comment]
Elevation, latitude, and longitude data is now on my github page. That attendance project will have to wait.

**Comment by guga31bb** [comment]
Info from PFR can't make it into the package because data needs to be available at completion of the game, so attendance probably isn't going to happen. For elevation and location, if you can convince Lee to add it to his games file (which we source in the package), we could definitely add that.
