### ISSUE TITLE
passer_player_name is na despite passer_player_id being populated

### ISSUE THREAD

**Issue by jeffgould231** [mrcaseb/nflfastR#6]
I discovered that there are some issues where name is an na value despite being a valid play. I did a little digging and found that this appears to be due NA values in (passer/rusher)_player_name even though (passer/rusher)_player_id is populated. This mostly seems to be a sporadic issue spread throughout the data on about 3000 plays, with the exception of the 2011 SF 49ers where the problem accounts for almost half of their offensive season

Below is some (messy) code that seems to fix the problem by text parsing the play description, at least for the 2011 SF team. Although string parsing isn't a strong suit of mine and I'm sure there's a better solution.

pbp_work <- pbp_all[pbp_all$season == 2011,] %>%
  distinct() %>%
  filter((pass == 1 | rush == 1), 
         !is.na(epa), 
         game_type == "REG", season == 2011, posteam == "SF", is.na(name)) %>%
  select(posteam, game_date, desc, passer_player_name, passer_player_id, rusher_player_name, rusher_player_id, name)

pbp_test <- pbp_work %>%
    mutate(temp_player_name = if_else(
      (is.na(passer_player_name) & !is.na(passer_player_id)),
      str_extract(desc, "[:upper:][:alpha:]+ [:upper:][:alpha:]+"),
      passer_player_name
    )) %>%
    mutate(passer_player_name = if_else(is.na(passer_player_name) & !is.na(passer_player_id),
                                        str_c(str_sub(temp_player_name,1,1), 
                                              str_trim(str_extract(temp_player_name, " [:upper:][:alpha:]+")), 
                                              sep = "."),
                                        passer_player_name))

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/48036549/80867603-fb5bc300-8c62-11ea-9337-ffb57b0a533c.png">

**Comment by guga31bb** [comment]
Those 49ers teams are a mess because they had Alex Smith and Aldon Smith so they used all sorts of different names for Alex Smith since "A.Smith" or "Al.Smith" wasn't unique for them.

We include a function that deals with most of this string parsing stuff (`clean_pbp()`), , but currently it breaks on Alex Smith so thanks for the reminder.

**Comment by mrcaseb** [comment]
In addition to Ben’s answer I would recommend anyway to use the Player Ids and join the player names in the version you like from the roster data. 
There is a complete roster data frame in the data repo you can use.

**Comment by guga31bb** [comment]
Ha, to give a different answer I think player Ids in the play-by-play are mostly useless because NFL doesn't fill them in on penalties. Pretty much everything I do uses player name + team to identify players

**Comment by mrcaseb** [comment]
I never checked it but it would be worth to have a look if this is true for the rs feed as well.

**Comment by jeffgould231** [comment]
I thought about using the roster data as well. I typically prefer to group by player name and id when possible as an extra redundancy for those same name/same team situations, but that’s not always possible for the situations Ben referenced

**Comment by mrcaseb** [comment]
> Ha, to give a different answer I think player Ids in the play-by-play are mostly useless because NFL doesn't fill them in on penalties. Pretty much everything I do uses player name + team to identify players

FYI Ben is completely right. IDs are messed up in the pbp data of the rs feed as well...

**Comment by jeffgould231** [comment]
This seems to do the trick. I checked it on the 2011 49ers and it went from about 60 Alex Smith plays to 600+
And this way it would be possible to group on both name and Id

`pbp_all <- readRDS("Data/pbp_all.rds") %>% filter(season > 2000)
rosters <- readRDs("Data/RostersAll.rds")

rosters_work <- rosters %>%
  mutate(playerName = str_c(str_sub(teamPlayers.firstName,1,1), teamPlayers.lastName, sep = ".")) %>%
  filter(teamPlayers.position %in% c("QB", "RB", "WR", "TE", "FB", "HB")) %>%
  select(team.season, playerName, team.abbr, teamPlayers.gsisId) %>%
  distinct()

pbp_work <- pbp_all %>%
  mutate(Id = ifelse(!is.na(passer_player_id), passer_player_id, 
                      ifelse(!is.na(rusher_player_id), rusher_player_id, 
                              NA))) %>%
  left_join(rosters_work, by = c("posteam" = "team.abbr", "season" = "team.season", "name" = "playerName")) %>%
  mutate(Id = ifelse(is.na(Id), teamPlayers.gsisId, Id)) %>%
  select(-teamPlayers.gsisId) %>%
  left_join(rosters_work, by = c("posteam" = "team.abbr", "season" = "team.season", "Id" = "teamPlayers.gsisId")) %>%
  mutate(name = ifelse(is.na(name), playerName, name)) %>%
  select(-playerName)`

**Comment by guga31bb** [comment]
I'm still working on this too, but one complication is making sure it works
on players with all sorts of names- there's people with apostrophes
(O'Donnell), hyphens (Jones-Drew), suffixes (Minshew II) and other stuff so
I'm trying to write it to catch everything. Hopefully within the next day
or two but I keep finding exceptions!

**Comment by mrcaseb** [comment]
Idea (could be silly):
The string parsing in the clean_pbp() function outputs the passer or rusher name in nearly all plays. 
We could group by passer_name and passer_id for alle plays. In most cases each name will have 2 IDs (the actual gsis-id from regular plays and NA from penalty plays). Can’t we fill the NA ids with the correct ids from non penalty plays? Must be possible...

**Comment by guga31bb** [comment]
This has been fixed, but note that we've changed how we parse the desc field: the parsed names are in `name`, `passer`, `rusher`, and `receiver`. I changed this because overwriting the original fields felt wrong. The original fields provided by NFL are `passer_player_name`, etc. These will generally not be filled in with penalties.
