### ISSUE TITLE
Very high negative air_yards values

### ISSUE THREAD

**Issue by bennivalur** [mrcaseb/nflfastR#60]
Am not sure if this is me understanding air_yards wrong or something is wrong in the data.

But I found five entries from 1999-2019 where the air_yards value is less than -50. I am guessing QBs aren't throwing the ball 50 yards behind the line of scrimmage.

These are the entries

play_id		air_yards		game_id         yards_after_catch  yards_gained
4188                -58.0	2007_02_MIN_DET		NaN           0.0
17939              -80.0        2007_07_TEN_HOU               88.0          8.0
10315              -93.0	2008_04_SF_NO      	NaN           0.0
37853              -66.0	2008_15_PIT_BAL		NaN           0.0
15355              -52.0	2009_06_PHI_OAK		NaN           0.0

**Comment by guga31bb** [comment]
I can't check these specific plays because there seems to be something wrong with your `play_id` values, but there's a known issue where `air_yards` is provided incorrectly from NFL, often on plays that cross the 50 yard line.

**Comment by guga31bb** [comment]
Yep these are wrong in the data the NFL provides. I typically deal with this by excluding plays with high negative air yards (for example in the CP model)
