### ISSUE TITLE
Loading multiple seasons

### ISSUE THREAD

**Issue by bentickle** [mrcaseb/nflfastR#61]
New to R so trying to learn using the beginners guide and I’m struggling to load multiple seasons after copying the code. Error in map...object seasons not found. Any help would be appreciated

**Comment by mrcaseb** [comment]
Since you didn't provide the exact code you were running I am guessing it is this
```r
seasons <- 2015:2019
pbp <- map_df(seasons, function(x) {
  readRDS(
    url(
      paste0("https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_",x,".rds")
    )
  )
})
```
The `map` function raises the error because you forgot to run the line 
```R
seasons <- 2015:2019
```

**Comment by bentickle** [comment]
thank you!
