### ISSUE TITLE
Inflated WR Targets

### ISSUE THREAD

**Issue by tstan97** [mrcaseb/nflfastR#62]
Michael Thomas targets/receptions 2019: 185/149

Trying to pull this using nflfastr:

wr<-pbp%>%select(receiver, desc, play_type,season, epa, play_id, week, yards_gained, season_type)%>%filter(play_type=='pass', receiver=='M.Thomas', season==2019, season_type=='REG')%>%group_by(receiver)

wr%>%summarize(mean_epa=mean(epa), ypc=mean(yards_gained), receptions=n())

 A tibble: 1 x 4
  receiver mean_epa   ypc receptions
  <chr>       <dbl> <dbl>      <int>
1 M.Thomas    0.527  9.15        190

Shows 190 targets instead of 185

After adding pass_complete==1 to filter(), it shows 151 receptions instead of 149.

A tibble: 1 x 4
  receiver mean_epa   ypc receptions
  <chr>       <dbl> <dbl>      <int>
1 M.Thomas    0.871  11.5        151

**Comment by guga31bb** [comment]
You're catching the 'M.Thomas' on the Rams too. Add posteam == 'NO' and you'll get 185 targets
