### ISSUE TITLE
Effect of Timeouts on EP Model

### ISSUE THREAD

**Issue by ajreinhard** [mrcaseb/nflfastR#63]
This might be something you're already aware of, so I apologize if that is the case, but I was exploring the expected points model and I was a little concerned with what I saw when I isolated on timeouts.  I looked at 1st & 10 for the home team at the 75 yardline as I assumed this would have a large sample size. It looks like the possession team having three timeouts is worth about 0.7 points more than having zero timeouts for the entirety of the first quarter of the half. This seems like a lot, but I'm sure very few teams have burned all their timeouts this quickly, so it may not matter much. My bigger concern is that just after the quarter-break, zero timeouts vaults up to having the highest expected points of the four categories. The "advantage" of having zero timeouts is pretty modest, but I dislike the idea that a team could technically improve their expected points by burning a timeout and doing nothing else. Zero timeouts has the highest EP output until about the two minute warning, where things balance out to the hierarchy that I initially expected to see.

I didn't look into this a ton yet, but it appears that this structure persists to some degree at other yardlines, downs, and model years. I figured I'd bring it here first and see if I was missing something.

````
library(nflfastR)
library(tidyverse)

expand.grid(
  'posteam_timeouts_remaining' = 0:3,
  'half_seconds_remaining' = 1800:1
  ) %>% 
  mutate(
    'season' = 2019,
    'home_team' = 'CLE',
    'posteam' = 'CLE',
    'roof' = 'outdoors',
    'down' = 1,
    'ydstogo' = 10,
    'yardline_100' = 75,
    'defteam_timeouts_remaining' = 3
  ) %>% 
  calculate_expected_points %>% 
  mutate(posteam_timeouts_remaining = factor(posteam_timeouts_remaining)) %>% 
  ggplot(aes(x = half_seconds_remaining, y = ep, color = posteam_timeouts_remaining, group = posteam_timeouts_remaining)) + 
  geom_line(size = 1.4) +
  scale_x_reverse(breaks = seq(0,1800,300)) +
  scale_color_manual(values = colorRampPalette(c('#8cf1ff','#00009e'))(4)) +
  labs(title = 'How Much is a Timeout Worth?',
       subtitle = '1st & 10 for Home Team at Own 25, Outdoors in 2019 Season with Full Timeouts for Opponent') +
  theme_light() +
  theme(legend.position = 'top')
````

**Comment by guga31bb** [comment]
Have not looked into this at all so thanks for raising it, and thanks for including code, makes it much easier to check. 

Just looking at 2018 & 2019, I found one game out of 534 where a team ran out of timeouts in the 1st or 3rd quarter (CAR against TB in 2018). For the entire 1999-2019 data, out of 726,902 pass or rush plays, 150 happened in the 1st or 3rd quarter with no possession team timeouts remaining. So while it looks weird, it's an artifact of having barely any training data to work with.

Why it changes at the quarter break is indeed a mystery as quarter isn't even an input into the model (there's just half seconds remaining)...

**Comment by guga31bb** [comment]
Replacing `ep` with `no_score_prob` in your code and it actually looks like it should, except for the timeouts = 0 part early in the half, which is clearly wrong
![image](https://user-images.githubusercontent.com/1425357/89237896-6ac6b300-d5c2-11ea-9d25-c033ebd869f8.png)

**Comment by guga31bb** [comment]
Closing this as I don't think it's a bug but rather a reflection of weird things happening in the small sample size of 0-timeouts early in half.

Over the offseason I want to take another look at the EP model and how it handles timeouts
