### ISSUE TITLE
Scoring odds on made FGs don't add to 1

### ISSUE THREAD

**Issue by sahil-bolar** [mrcaseb/nflfastR#66]
On a few of the made FGs, the scoring odds are nonzero for the fg_prob (as it should be), but zero for all other types of scores.
![image](https://user-images.githubusercontent.com/63615347/91501866-31652880-e88c-11ea-9618-c86503a6071e.png)
This results in the scoring probabilities not adding up to 1, but instead just adding up to the fg_prob itself.

For instance, see play_id 2179 from game_id 2019090800: J.Slye 46 yard field goal is GOOD. On this play the FG prob is 0.75, but the TD prob, safety prob, opposing FG prob, opposing TD prob, opposing safety prob, and no score prob are all 0. 

This issue affects the EP (if only slightly), to the point where it suggests that a Patrick Mahomes sack was positive EPA because the ensuing FG attempt had zeroes for all opposing score probabilities.

**Comment by guga31bb** [comment]
Thanks for sending this in! 

It is possible you're working with an older version of the data as I'm getting different EP. On this particular play, all the other probabilities are 0 because the play happened as time expired in the first half:

``` r
games <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2019.rds'))

games %>% filter(old_game_id == 2019090800, play_id == 2179) %>% select(desc, ep, opp_fg_prob)

# A tibble: 1 x 3
  desc                                                                  ep opp_fg_prob
  <chr>                                                              <dbl>       <dbl>
1 (:02) 4-J.Slye 46 yard field goal is GOOD, Center-44-J.Jansen, Ho~  2.23           0
```

I did find one sack that had positive EPA (game ID '2019_07_ARI_NYG' and play ID 3905). This is related to this issue: https://github.com/mrcaseb/nflfastR/issues/30#issuecomment-649732697

**Comment by guga31bb** [comment]
Although `no_score_prob` should be higher in the example you gave, though this doesn't affect `EP`.

**Comment by mrcaseb** [comment]
Is this issue still a thing? Looks like we can close it?!

**Comment by guga31bb** [comment]
Yeah even though it doesn't change EP, no score prob is wrong so I need to
look into this

**Comment by sahil-bolar** [comment]
Sorry for the late response, but after using the new data my EP matches up. And yeah, it looks to me like all the field goal attempts where the total probability don't add up to 1 occur when half_seconds_remaining <= 5, so it doesn't look like it affects EP.
