### ISSUE TITLE
Updated weekly for 2020 season

### ISSUE THREAD

**Issue by Coop197823** [mrcaseb/nflfastR#68]
Not an issue per se, but a question.  I have been pulling updated weekly data during the live seasons through  derek-adair/nflgame python API.  With the changes in the nfl API, it looks like they may no longer be able to build that weekly databases and I am looking for alternatives to grab my nfl data. 

Will this datawarehouse be updated at the end of each nfl week, or will i need to scrape on say like every Tuesday morning after the nfl games have been played?

**Comment by guga31bb** [comment]
Which data warehouse are you referring to? If it's helpful, our intention is to have games available shortly after they finish.

**Comment by Coop197823** [comment]
Thanks for getting back to me so quickly!  If I understand your code, I am assuming this data after you guys have scraped it goes into your datawarehouse (guga31bb) correct, where is then resides with all the other data (1999-20019)?  I am just looking through your vignettes and looking at code in particular:  

`data <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2019.rds'))`

and wondering if I can use those same call to grab 2020 data in the same manner

I am looking for play by play data, and am just trying to make sure I can access the most current week after the games have been played.  Thanks!

**Comment by guga31bb** [comment]
> and wondering if I can use those same call to grab 2020 data in the same manner
> 
> I am looking for play by play data, and am just trying to make sure I can access the most current week after the games have been played. Thanks!

Yep this is the plan, with the caveat that this is all new and hasn't actually been tested during a season.
