### ISSUE TITLE
Descriptions with "backward pass" have inconsistent "pass" and "rush" fields

### ISSUE THREAD

**Issue by evjeff** [mrcaseb/nflfastR#76]
Hi - I love this project and have been exploring the data a little and noticed this and hadn't seen it mentioned in any issues before, so just wanted to make sure this is by design.

All of these plays are listed with a "pass"==1, except one play (#2781 2018_13_KC_OAK) where the word pass is capitalized (Backward Pass).

I think a lot of these plays should be rush==1, pass==0?

Here are some of the examples:

game_id	play_id    play_type	    pass	pass_attempt	rush	   rush_attempt	desc						

2011_03_BAL_STL | 668 | run | 1 | 0.0 | 0 | 1.0 | (6:43) 82-T.Smith right end pushed ob at BAL 30 for 10 yards (27-Q.Mikell). Backward pass.

2011_15_CIN_STL | 1210 | pass | 1 | 1.0 | 0 | 0.0 | (9:28) 10-K.Clemens pass incomplete short left to 18-A.Pettis. Backward pass from 34-Norwood to 10-Clemens

2013_06_WAS_DAL | 502 | run | 1 | 0.0 | 0 | 1.0 | (6:06) (Shotgun) 89-S.Moss right end to DAL 35 for -3 yards (99-G.Selvie). Backward pass to Moss.

2018_13_KC_OAK | 2781 | run | 0 | 0.0 | 1 | 1.0 | (7:17) **Backward Pass** (Shotgun) 10-T.Hill right end pushed ob at OAK 1 for 4 yards (50-N.Morrow).

**Comment by guga31bb** [comment]
This affects the Aiyuk TD in this game https://rbsdm.com/stats/box_scores/?_inputs_&type=%22reg%22&away=%22PHI%22&home=%22SF%22&year=%222020%22
