### ISSUE TITLE
update to SQLite db fails on error in pbp_data$qtr

### ISSUE THREAD

**Issue by MargareeMan** [mrcaseb/nflfastR#80]
The update runs until just after the download of missing games and the addition of two additional variables:

"added game variables
added nflscrapR variables
added ep variables
added air_yac_ep variables"

But it fails and aborts without altering the database:

Error in if (any(pbp_data$qtr > 4)) { : 
  missing value where TRUE/FALSE needed

**Comment by guga31bb** [comment]
Please update the package with the version on github- see our tweets about
this

**Comment by MargareeMan** [comment]
sorry, I do not follow your tweets.  Will now do so.  Thanks.
Works fine.
Your twitter stream is awesome.  (I am 71 yrs old, just in case "awesome" is inappropriate)
