### ISSUE TITLE
Null values for Week 1 2020 Scores in fast_scraper_schedules

### ISSUE THREAD

**Issue by aggieed97** [mrcaseb/nflfastR#81]
Wasn't sure if the score results for the individual games were supposed to be populated when running the fast_scraper_schedules function. At the moment there are no scores (3:45 AM CST on 9/18/2020).

![image](https://user-images.githubusercontent.com/35159749/93576957-1785a580-f961-11ea-8341-cce2ddd889e7.png)

**Comment by mrcaseb** [comment]
That's indeed a forgotten automation process. Thanks for catching this. I'll look into it.

**Comment by mrcaseb** [comment]
Should be fixed now.
