### ISSUE TITLE
James O'Shaughnessy CP missing

### ISSUE THREAD

**Issue by ajreinhard** [mrcaseb/nflfastR#91]
All targets to JAX TE James O'Shaughnessy are coming back with NA in the cp field. I suspect this is some issue with how the regex on line 61 of helper_add_cp_cpoe.R is handling receiver names with apostrophes. I also checked 2019 and there is another player (N.O'Leary) with the same issue.
```
pbp_df <- readRDS(url('https://raw.githubusercontent.com/guga31bb/nflfastR-data/master/data/play_by_play_2020.rds'))

# all missing cp targets
pbp_df %>% 
  filter(is.na(cp) & pass_attempt == 1 & sack == 0 & !is.na(receiver) & !is.na(air_yards) & two_point_attempt==0) %>% 
  pull(receiver) %>% 
  table

# all apostrophe targets
pbp_df %>% 
  filter(grepl('\'',receiver)) %>% 
  pull(cp) %>% 
  is.na %>% 
  table
```

**Comment by guga31bb** [comment]
Good catch and easy fix- thanks!
